/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Cup { 
    company?: string;
    courtCounter?: number;
    deleted?: boolean;
    description?: string;
    endDateTime?: Date;
    imageUrl?: string;
    name?: string;
    place?: string;
    registrationEndTime?: Date;
    startDateTime?: Date;
}
