/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';


export interface Team { 
    company?: string;
    deleted?: boolean;
    imageUrl?: string;
    leaders?: Array<User>;
    name?: string;
    users?: Array<User>;
}
