/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface User { 
    accessToken?: string;
    companyName?: string;
    deleted?: boolean;
    email?: string;
    emailVerified?: boolean;
    googleName?: string;
    id?: string;
    imageUrl?: string;
    provider?: User.ProviderEnum;
    providerId?: string;
}
export namespace User {
    export type ProviderEnum = 'local' | 'facebook' | 'google' | 'github';
    export const ProviderEnum = {
        Local: 'local' as ProviderEnum,
        Facebook: 'facebook' as ProviderEnum,
        Google: 'google' as ProviderEnum,
        Github: 'github' as ProviderEnum
    };
}
