jdk: openjdk11
language: java
services:
  - postgresql
before_script:
  - createuser sport_event_organizer
  - psql -c "alter user sport_event_organizer with encrypted password '123456';" -U postgres
  - psql -c "create database sport_event_organizer;" -U postgres
  - psql -c "grant all privileges on database sport_event_organizer to sport_event_organizer;" -U postgres
script:
  - "cd ./server"
  - "./mvnw clean test"
