/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Cup } from '../model/cup';
import { Team } from '../model/team';
import { User } from '../model/user';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CupResourceService {

    protected basePath = 'https://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * addOrganizer
     * 
     * @param cupName cupName
     * @param googleName googleName
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addOrganizerUsingPOST(cupName: string, googleName: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public addOrganizerUsingPOST(cupName: string, googleName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public addOrganizerUsingPOST(cupName: string, googleName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public addOrganizerUsingPOST(cupName: string, googleName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cupName === null || cupName === undefined) {
            throw new Error('Required parameter cupName was null or undefined when calling addOrganizerUsingPOST.');
        }

        if (googleName === null || googleName === undefined) {
            throw new Error('Required parameter googleName was null or undefined when calling addOrganizerUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<any>(`${this.basePath}/cup/organizers/add/${encodeURIComponent(String(cupName))}/${encodeURIComponent(String(googleName))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * applyTeam
     * 
     * @param cupName cupName
     * @param teamName teamName
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public applyTeamUsingPOST(cupName: string, teamName: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public applyTeamUsingPOST(cupName: string, teamName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public applyTeamUsingPOST(cupName: string, teamName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public applyTeamUsingPOST(cupName: string, teamName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cupName === null || cupName === undefined) {
            throw new Error('Required parameter cupName was null or undefined when calling applyTeamUsingPOST.');
        }

        if (teamName === null || teamName === undefined) {
            throw new Error('Required parameter teamName was null or undefined when calling applyTeamUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<any>(`${this.basePath}/cup/apply/${encodeURIComponent(String(cupName))}/${encodeURIComponent(String(teamName))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * approveTeam
     * 
     * @param cupName cupName
     * @param teamName teamName
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public approveTeamUsingPOST(cupName: string, teamName: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public approveTeamUsingPOST(cupName: string, teamName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public approveTeamUsingPOST(cupName: string, teamName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public approveTeamUsingPOST(cupName: string, teamName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cupName === null || cupName === undefined) {
            throw new Error('Required parameter cupName was null or undefined when calling approveTeamUsingPOST.');
        }

        if (teamName === null || teamName === undefined) {
            throw new Error('Required parameter teamName was null or undefined when calling approveTeamUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<any>(`${this.basePath}/cup/approve/${encodeURIComponent(String(cupName))}/${encodeURIComponent(String(teamName))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * createCup
     * 
     * @param cup cup
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createCupUsingPOST(cup: Cup, observe?: 'body', reportProgress?: boolean): Observable<Cup>;
    public createCupUsingPOST(cup: Cup, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Cup>>;
    public createCupUsingPOST(cup: Cup, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Cup>>;
    public createCupUsingPOST(cup: Cup, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cup === null || cup === undefined) {
            throw new Error('Required parameter cup was null or undefined when calling createCupUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Cup>(`${this.basePath}/cup`,
            cup,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deleteCup
     * 
     * @param name name
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteCupUsingDELETE(name: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteCupUsingDELETE(name: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteCupUsingDELETE(name: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteCupUsingDELETE(name: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling deleteCupUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/cup/${encodeURIComponent(String(name))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deleteOrganizer
     * 
     * @param cupName cupName
     * @param googleName googleName
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteOrganizerUsingPOST(cupName: string, googleName: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteOrganizerUsingPOST(cupName: string, googleName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteOrganizerUsingPOST(cupName: string, googleName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteOrganizerUsingPOST(cupName: string, googleName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cupName === null || cupName === undefined) {
            throw new Error('Required parameter cupName was null or undefined when calling deleteOrganizerUsingPOST.');
        }

        if (googleName === null || googleName === undefined) {
            throw new Error('Required parameter googleName was null or undefined when calling deleteOrganizerUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<any>(`${this.basePath}/cup/organizers/delete/${encodeURIComponent(String(cupName))}/${encodeURIComponent(String(googleName))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAllCupsByCompany
     * 
     * @param company company
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllCupsByCompanyUsingGET(company: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Cup>>;
    public getAllCupsByCompanyUsingGET(company: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Cup>>>;
    public getAllCupsByCompanyUsingGET(company: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Cup>>>;
    public getAllCupsByCompanyUsingGET(company: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (company === null || company === undefined) {
            throw new Error('Required parameter company was null or undefined when calling getAllCupsByCompanyUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<Cup>>(`${this.basePath}/cup/company/${encodeURIComponent(String(company))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAllCupsByPlace
     * 
     * @param place place
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllCupsByPlaceUsingGET(place: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Cup>>;
    public getAllCupsByPlaceUsingGET(place: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Cup>>>;
    public getAllCupsByPlaceUsingGET(place: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Cup>>>;
    public getAllCupsByPlaceUsingGET(place: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (place === null || place === undefined) {
            throw new Error('Required parameter place was null or undefined when calling getAllCupsByPlaceUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<Cup>>(`${this.basePath}/cup/place/${encodeURIComponent(String(place))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAllCups
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllCupsUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<Cup>>;
    public getAllCupsUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Cup>>>;
    public getAllCupsUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Cup>>>;
    public getAllCupsUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<Cup>>(`${this.basePath}/cup`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getAppliedTeams
     * 
     * @param cupName cupName
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAppliedTeamsUsingGET(cupName: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Team>>;
    public getAppliedTeamsUsingGET(cupName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Team>>>;
    public getAppliedTeamsUsingGET(cupName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Team>>>;
    public getAppliedTeamsUsingGET(cupName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cupName === null || cupName === undefined) {
            throw new Error('Required parameter cupName was null or undefined when calling getAppliedTeamsUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<Team>>(`${this.basePath}/cup/${encodeURIComponent(String(cupName))}/applied`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getApprovedTeams
     * 
     * @param cupName cupName
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getApprovedTeamsUsingGET(cupName: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Team>>;
    public getApprovedTeamsUsingGET(cupName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Team>>>;
    public getApprovedTeamsUsingGET(cupName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Team>>>;
    public getApprovedTeamsUsingGET(cupName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cupName === null || cupName === undefined) {
            throw new Error('Required parameter cupName was null or undefined when calling getApprovedTeamsUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<Team>>(`${this.basePath}/cup/${encodeURIComponent(String(cupName))}/approved`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getCupByName
     * 
     * @param name name
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCupByNameUsingGET(name: string, observe?: 'body', reportProgress?: boolean): Observable<Cup>;
    public getCupByNameUsingGET(name: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Cup>>;
    public getCupByNameUsingGET(name: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Cup>>;
    public getCupByNameUsingGET(name: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling getCupByNameUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Cup>(`${this.basePath}/cup/${encodeURIComponent(String(name))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getCupByOrganizer
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCupByOrganizerUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<Cup>>;
    public getCupByOrganizerUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Cup>>>;
    public getCupByOrganizerUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Cup>>>;
    public getCupByOrganizerUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<Cup>>(`${this.basePath}/cup/organizer`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getCupsByParticipation
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCupsByParticipationUsingGET(observe?: 'body', reportProgress?: boolean): Observable<Array<Cup>>;
    public getCupsByParticipationUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Cup>>>;
    public getCupsByParticipationUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Cup>>>;
    public getCupsByParticipationUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<Cup>>(`${this.basePath}/cup/my-cups`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getOrganizers
     * 
     * @param cupName cupName
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getOrganizersUsingGET(cupName: string, observe?: 'body', reportProgress?: boolean): Observable<Array<User>>;
    public getOrganizersUsingGET(cupName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<User>>>;
    public getOrganizersUsingGET(cupName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<User>>>;
    public getOrganizersUsingGET(cupName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cupName === null || cupName === undefined) {
            throw new Error('Required parameter cupName was null or undefined when calling getOrganizersUsingGET.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<Array<User>>(`${this.basePath}/cup/organizers/${encodeURIComponent(String(cupName))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * refuseTeam
     * 
     * @param cupName cupName
     * @param teamName teamName
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public refuseTeamUsingPOST(cupName: string, teamName: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public refuseTeamUsingPOST(cupName: string, teamName: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public refuseTeamUsingPOST(cupName: string, teamName: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public refuseTeamUsingPOST(cupName: string, teamName: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cupName === null || cupName === undefined) {
            throw new Error('Required parameter cupName was null or undefined when calling refuseTeamUsingPOST.');
        }

        if (teamName === null || teamName === undefined) {
            throw new Error('Required parameter teamName was null or undefined when calling refuseTeamUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<any>(`${this.basePath}/cup/refuse/${encodeURIComponent(String(cupName))}/${encodeURIComponent(String(teamName))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateCup
     * 
     * @param cup cup
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateCupUsingPUT(cup: Cup, observe?: 'body', reportProgress?: boolean): Observable<Cup>;
    public updateCupUsingPUT(cup: Cup, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Cup>>;
    public updateCupUsingPUT(cup: Cup, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Cup>>;
    public updateCupUsingPUT(cup: Cup, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cup === null || cup === undefined) {
            throw new Error('Required parameter cup was null or undefined when calling updateCupUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // authentication (JWT) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<Cup>(`${this.basePath}/cup`,
            cup,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
