version: "3"
services:
  elastic:
    image: elasticsearch:6.8.0
    networks: 
    - searchnetwork
    ports: 
    - 9200:9200
    - 9300:9300
    environment: 
    - discovery.type=single-node
  kibana:
    image: kibana:6.8.0
    networks: 
    - searchnetwork
    ports: 
    - 5601:5601


networks:
  searchnetwork: